### ISSUE TITLE
installation tutorial

### ISSUE THREAD

**Issue by Aestios** [bricefrisco/NamesLoL-Archive-2#3]
Hello, would it be possible to have a little tutorial to install locally? thank you

**Comment by bricefrisco** [comment]
The repository has moved as has the tech stack.

Local installation instructions can be found on the frontend repository and can be run locally with ease.
Running the back-end is a bit tricker, as an AWS account is needed for resources such as DynamoDB, etc.

I've added an installation guide to the README on the new [frontend](https://github.com/bricefrisco/NamesLoL-Frontend) as well as the [backend](https://github.com/bricefrisco/NamesLoL) repositories.
